version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - rm -fr /var/cache/yum/*
      - yum clean all
      - yum -y --skip-broken update
      - yum -y install ibus-kkc vlgothic-* glibc-locale-source glibc-langpack-en

  pre_build:
    commands:
      - localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
      - export LANG="ja_JP.UTF-8"
      - export LANGUAGE="ja_JP:ja"
      - export LC_ALL="ja_JP.UTF-8"

  build:
    commands:
      - ./gradlew build -x test

artifacts:
  files:
#    - ./build/libs/dbaas_cassandra-0.0.1-SNAPSHOT.jar
     - ./dbaas_cassandra-0.0.1-SNAPSHOT.jar